BaseUrl= "https://netbrain.github.io"
LanguageCode= "en"
Title= "Kim Eik"
theme = "PaperMod"

[pagination]
pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#DisqusShortname = "netbrain"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "A passionate programmer."
  cover = "/images/bg.jpg"
  author = "Kim Eik"
  authorlocation = "Norway"
#  authorwebsite = "http://vjeantet.fr"
  bio= "Husband // Father // Thinker // Developer"
  logo = "/images/logo.png"
#  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
#  RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "netbrain"
#  twitterName = "vjeantet"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "Home"
  weight = -130
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"
